package com.spartajet.gear.match.mybatis.mapper

import com.spartajet.gear.match.mybatis.bean.Gear
import org.apache.ibatis.annotations.Mapper

/**
 * @description
 * @create 2017-05-29 上午11:00
 * @email spartajet.guo@gmail.com
 */
@Mapper
interface GearMapper {
    /**
     * Select all gears list.

     * @return the list
     */
    fun selectAllGears(): List<Gear>
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gear
     * @param id the id
     * *
     * *
     * @return the int
     * *
     * *
     * @mbggenerated
     */
    fun deleteByPrimaryKey(id: Long): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gear
     * @param record the record
     * *
     * *
     * @return the int
     * *
     * *
     * @mbggenerated
     */
    fun insert(record: Gear): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gear
     * @param record the record
     * *
     * *
     * @return the int
     * *
     * *
     * @mbggenerated
     */
    fun insertSelective(record: Gear): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gear
     * @param id the id
     * *
     * *
     * @return the gear
     * *
     * *
     * @mbggenerated
     */
    fun selectByPrimaryKey(id: Int?): Gear

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gear
     * @param record the record
     * *
     * *
     * @return the int
     * *
     * *
     * @mbggenerated
     */
    fun updateByPrimaryKeySelective(record: Gear): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gear
     * @param record the record
     * *
     * *
     * @return the int
     * *
     * *
     * @mbggenerated
     */
    fun updateByPrimaryKey(record: Gear): Int

    /**
     * Total gears size int.
     * @return the size
     */
    fun totalGearsSize(): Int
}